### PR TITLE
Update branch tracking to main from ftr-serverless

### PR DESCRIPTION
**Pull request by gregcusack**
hey Erika! i'm updating the Escra git repo to make it open source for the conference! all the serverless repos got merged into "main" branches. so updated your cloudlab repo to reflect that. but want to make sure you're ok with the update! feel free to merge or not merge or whatever! just let me know!
Thank you!
- Greg

### CODE REVIEW

**Comment by hunhoffe** [comment]
Hi Greg! Did you test it by creating a cloudlab experiment after you made the changes? Just wanted to double check before I proceed!

**Comment by gregcusack** [comment]
yesss i did! but realized now that i didn't fully update it. has to track the new "Escra" repo. so instantiating now and trying again!

**Comment by gregcusack** [comment]
closing since this is stale

**Comment by hunhoffe** [comment]
Hi Greg, is this something you still wanted to add?

Edit: saw new PR, please disregard comment.

**Pull request closed without merging**
